export const USER_ROLES:readonly string[]=[
    "VOC_ROLE_ADMIN",
    "VOC_ROLE_PROFESSOR",
    "VOC_ROLE_ENGINEER",
    "VOC_ROLE_DOCTOR",
    "VOC_ROLE_TEACHER",
    "VOC_ROLE_GRADUATE_STUDENT",
    "VOC_ADMINISTRATIVE_OFFICER"
];
export const USER_TEMPORARY_ROLES:readonly string[]=[
    "VOC_TEMPORARY_ROLE_DEAN",
    "VOC_TEMPORARY_ROLE_ADMINISTRATIVE_DEPUTY",
    "VOC_TEMPORARY_ROLE_SCIENTIFIC_VICE",
    "VOC_TEMPORARY_ROLE_HEAD_OF_DEPARTMENT",
    "VOC_TEMPORARY_ROLE_HEAD_OF_CIRCLE",
    "VOC_TEMPORARY_ROLE_HEAD_OF_EXAMINATIONS_DEPARTMENT",
    "VOC_TEMPORARY_ROLE_TIMEKEEPER",
    "VOC_TEMPORARY_ROLE_HEAD_OF_STUDENT_AFFAIRS"
];

export const USER_PROPERTIES=[
    "VOC_PROPERTY_BOARD_MEMBER",
    "VOC_PROPERTY_TECHNICAL_BOARD_MEMBER",
]