version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql_server
    restart: always
    env_file: ./env/mysql.env
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - '80:80'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: ./env/backend.env
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '4200:4200'
  #     - '49153:49153'
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

volumes:
  db-data: